# Antes de empezar :
   - Estos ejercicios están relacionados con las lecciones Subconjunto y Estadísticas descriptivas.
   - Tenga en cuenta que necesitará utilizar algunas de las funciones que aprendió en las lecciones anteriores.
   - Todos los conjuntos de datos se proporcionan en la carpeta `your-code` de este laboratorio.
   - Elabora tus códigos y resultados tanto como puedas.
   - Esfuérzate al máximo para responder a las preguntas y completar las tareas y, sobre todo, ¡¡¡disfruta del proceso!!!

#### Importa todas las librerías necesarias

In [3]:
import pandas as pd

# Desafío 1

#### En este reto utilizaremos el archivo `Temp_States.csv`. 

#### Primero impórtalo en un marco de datos llamado `temp`.

In [4]:
temp =  pd.read_csv('Temp_States.csv', delimiter = ',')

#### Print `temp`

In [5]:
temp

         City        State  Temperature
0         NYC     New York    19.444444
1      Albany     New York     9.444444
2     Buffalo     New York     3.333333
3    Hartford  Connecticut    17.222222
4  Bridgeport  Connecticut    14.444444
5      Treton   New Jersey    22.222222
6      Newark   New Jersey    20.000000

#### Explore los tipos de datos del marco de datos Temp. ¿Qué tipo de datos tenemos? Comenta tu resultado.

In [6]:
temp.dtypes

# ¿Que son los datos object?

City            object
State           object
Temperature    float64
dtype: object

#### Selecciona las filas en las que el estado es New York

In [7]:
temp[temp['State'] == 'New York']

      City     State  Temperature
0      NYC  New York    19.444444
1   Albany  New York     9.444444
2  Buffalo  New York     3.333333

#### ¿Cuál es la temperatura media de las ciudades de Nueva York?

In [8]:

temp[temp['State'] == 'New York']['Temperature'].mean().round(1)

np.float64(10.7)

#### Queremos conocer las ciudades y estados con temperaturas superiores a 15 grados centígrados.

In [9]:
temp[temp['Temperature'] > 15][['City', 'State']]

       City        State
0       NYC     New York
3  Hartford  Connecticut
5    Treton   New Jersey
6    Newark   New Jersey

#### Ahora, devuelva sólo las ciudades que tengan una temperatura superior a 15 grados centígrados.

In [10]:
temp[temp['Temperature'] > 15][['City']]

       City
0       NYC
3  Hartford
5    Treton
6    Newark

#### Queremos saber qué ciudades tienen una temperatura superior a 15 grados Celcius e inferior a 20 grados Celcius

*Pista: Primero escriba la condición y luego seleccione las filas.

In [11]:
temp[(temp['Temperature'] > 15) & (temp['Temperature'] < 20)][['City']]

       City
0       NYC
3  Hartford

In [12]:
temp['State'].value_counts()

State
New York       3
Connecticut    2
New Jersey     2
Name: count, dtype: int64

#### Halla la media y la desviación estándar de la temperatura de cada estado.

*Pista: Utiliza las funciones de la lección Manipulación de datos*.

In [13]:
temp.groupby('State')['Temperature'].describe()[['mean','std']]

                  mean       std
State
Connecticut  15.833333  1.964186
New Jersey   21.111111  1.571348
New York     10.740741  8.133404

# Desafío 2

#### Cargar el fichero `employee.csv` en un DataFrame. Llama al dataframe `employee`.

In [14]:
employee = pd.read_csv('Employee.csv')

employee.head()

     Name Department Education Gender      Title  Years  Salary
0    Jose         IT  Bachelor      M    analyst      1      35
1   Maria         IT    Master      F    analyst      2      30
2   David         HR    Master      M    analyst      2      30
3   Sonia         HR  Bachelor      F    analyst      4      35
4  Samuel      Sales    Master      M  associate      3      55

#### Explore los tipos de datos del marco de datos Temp. Comenta tus resultados

In [15]:
employee.dtypes

Name          object
Department    object
Education     object
Gender        object
Title         object
Years          int64
Salary         int64
dtype: object

#### Muestre visualmente la distribución de frecuencias (histograma) del conjunto de datos de empleados. Describa en pocas palabras estos histogramas.

In [16]:
# your answer here

In [17]:
# YOUR CODE HERE

In [18]:
# YOUR CODE HERE

#### ¿Cuál es el salario medio en esta empresa?

In [19]:
employee['Salary'].mean().round(2)

np.float64(48.89)

#### ¿Cuál es el salario más alto?

In [20]:
employee[employee['Salary'] == employee['Salary'].max()][['Salary']]

   Salary
6      70
8      70

#### ¿Cuál es el salario más bajo?

In [21]:
employee[employee['Salary'] == employee['Salary'].min()][['Salary']]

   Salary
1      30
2      30

#### ¿Quiénes son los empleados con el salario más bajo?

In [22]:
employee[employee['Salary'] == employee['Salary'].min()][['Name','Salary']]

    Name  Salary
1  Maria      30
2  David      30

#### ¿Podría darnos toda la información sobre un empleado llamado David?

In [23]:
employee[employee['Name'] == 'David']

    Name Department Education Gender    Title  Years  Salary
2  David         HR    Master      M  analyst      2      30

#### ¿Podría dar sólo el sueldo de David?

In [24]:
employee[employee['Name'] == 'David'][['Name','Salary']]

    Name  Salary
2  David      30

#### Printea todas las líneas en las que el cargo es asociado

In [25]:
employee[employee['Title'] == 'associate']

     Name Department Education Gender      Title  Years  Salary
4  Samuel      Sales    Master      M  associate      3      55
5     Eva      Sales  Bachelor      F  associate      2      55
7   Pedro         IT       Phd      M  associate      7      60

#### Printea las 3 primeras filas de tu dataframe

##### Consejo : Hay 2 maneras de hacerlo. Hazlo de las dos maneras

In [26]:
employee.head(3)

    Name Department Education Gender    Title  Years  Salary
0   Jose         IT  Bachelor      M  analyst      1      35
1  Maria         IT    Master      F  analyst      2      30
2  David         HR    Master      M  analyst      2      30

In [27]:
employee.iloc[:3]

    Name Department Education Gender    Title  Years  Salary
0   Jose         IT  Bachelor      M  analyst      1      35
1  Maria         IT    Master      F  analyst      2      30
2  David         HR    Master      M  analyst      2      30

#### ¿Encuentra a los empleados cuyo cargo es asociado y cuyo salario es superior a 55?

In [28]:
employee[(employee['Title'] == 'associate') & (employee['Salary'] > 55)]

    Name Department Education Gender      Title  Years  Salary
7  Pedro         IT       Phd      M  associate      7      60

#### Agrupa a los empleados en función del número de años que llevan trabajando. ¿Cuáles son los salarios medios de cada grupo?

In [29]:
employee.groupby('Years')[['Salary']].mean()

          Salary
Years
1      35.000000
2      38.333333
3      55.000000
4      35.000000
7      60.000000
8      70.000000

#### ¿Cuál es el salario medio por título?

In [30]:
employee.groupby('Title')[['Salary']].mean()

              Salary
Title
VP         70.000000
analyst    32.500000
associate  56.666667

#### Muestra un resumen visual de los datos utilizando boxplot. ¿Cuáles son los cuartiles primero y tercero? Comenta tus resultados.

* Pista : Cuantiles vs Cuartiles*.
En Probabilidad y Estadística, los cuantiles son puntos de corte que dividen el rango de una distribución de probabilidad en intervalos continuos con probabilidades iguales. Cuando la división es en cuatro partes, los valores de la variable correspondientes al 25%, 50% y 75% de la distribución total se denominan cuartiles.

In [31]:
import seaborn as sns

In [32]:
# print first quartile here

In [33]:
# print third quartile here

#### ¿Es diferente el salario medio por género?

In [34]:
employee.groupby('Gender')[['Salary']].mean()

        Salary
Gender
F         47.5
M         50.0

#### Encuentra el mínimo, la media y el máximo de todas las columnas numéricas para cada Departamento.

##### Sugerencia: Utiliza las funciones de la lección Manipulación de Datos

In [35]:
employee.groupby('Department')['Salary'].describe()[['min','mean','max']]

             min   mean   max
Department
HR          30.0  45.00  70.0
IT          30.0  48.75  70.0
Sales       55.0  55.00  55.0

In [36]:
employee.groupby('Department')['Years'].describe()[['min','mean','max']]

            min      mean  max
Department
HR          2.0  4.666667  8.0
IT          1.0  4.500000  8.0
Sales       2.0  2.500000  3.0

### Pregunta bonus

#### Para cada departamento, calcule la diferencia entre el salario máximo y el salario mínimo.

##### * Sugerencia: pruebe a utilizar `agg` o `apply` y `lambda`*.

In [37]:
# your answer here

# Desafío 3

#### Abra el conjunto de datos Orders.csv. Nombre el conjunto de datos pedidos

In [38]:
orders = pd.read_csv('Orders.csv')

#### Explore su conjunto de datos observando los tipos de datos y las estadísticas de resumen. Comenta tus resultados

In [39]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397924 entries, 0 to 397923
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0    397924 non-null  int64
 1   InvoiceNo     397924 non-null  int64
 2   StockCode     397924 non-null  object
 3   year          397924 non-null  int64
 4   month         397924 non-null  int64
 5   day           397924 non-null  int64
 6   hour          397924 non-null  int64
 7   Description   397924 non-null  object
 8   Quantity      397924 non-null  int64
 9   InvoiceDate   397924 non-null  object
 10  UnitPrice     397924 non-null  float64
 11  CustomerID    397924 non-null  int64
 12  Country       397924 non-null  object
 13  amount_spent  397924 non-null  float64
dtypes: float64(2), int64(8), object(4)
memory usage: 42.5+ MB

In [40]:
orders.head()

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

#### ¿Cuál es el precio medio de compra?

In [41]:
orders.groupby('InvoiceNo')[['amount_spent']].sum().sort_values('amount_spent')

           amount_spent
InvoiceNo
578841             0.00
564651             0.00
568384             0.00
543599             0.00
570554             0.38
...                 ...
556917         22775.93
567423         31698.16
556444         38970.00
541431         77183.60
581483        168469.60

[18536 rows x 1 columns]

In [42]:
orders[orders['InvoiceNo'] == 578841]

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
370473,502122,578841,84826,2011,11,5,15,asstd design 3d paper stickers,12540,2011-11-25 15:57:00,0.0,13256,United Kingdom,0.0

In [43]:
orders.groupby('InvoiceNo')[['amount_spent']].sum().mean()

amount_spent    480.762187
dtype: float64

#### ¿Cuáles fueron los precios de compra más altos y más bajos?

In [44]:
orders.groupby('InvoiceNo')[['amount_spent']].sum().max()

amount_spent    168469.6
dtype: float64

In [45]:
orders.groupby('InvoiceNo')[['amount_spent']].sum().min()

amount_spent    0.0
dtype: float64

#### Seleccione todos los clientes que tenemos en España

In [61]:

orders[orders['Country'] == 'Spain'][['CustomerID', 'Country']].drop_duplicates().sort_values(by = 'CustomerID')

        CustomerID Country
113099       12354   Spain
116553       12417   Spain
41390        12421   Spain
391792       12442   Spain
352636       12445   Spain
306993       12448   Spain
162904       12450   Spain
289129       12454   Spain
147386       12455   Spain
53374        12462   Spain
29804        12484   Spain
49687        12502   Spain
55336        12507   Spain
37428        12510   Spain
336389       12538   Spain
31390        12539   Spain
17368        12540   Spain
70307        12541   Spain
320987       12544   Spain
88639        12545   Spain
254077       12546   Spain
70657        12547   Spain
169315       12548   Spain
250565       12550   Spain
23288        12551   Spain
180343       12556   Spain
4250         12557   Spain
103106       12596   Spain
79781        12597   Spain
13974        17097   Spain

#### ¿Cuántos clientes tenemos en España?
##### Pista : Utiliza value_counts()

In [63]:

orders[orders['Country'] == 'Spain'][['CustomerID', 'Country']].drop_duplicates().sort_values(by = 'CustomerID').value_counts('Country')

Country
Spain    30
Name: count, dtype: int64

#### Selecciona todos los clientes que han comprado más de 50 artículos ?

In [119]:
temp01 = orders.groupby(by = 'CustomerID')[['Quantity']].count()

temp01[temp01['Quantity'] > 50]

            Quantity
CustomerID
12347            182
12349             73
12352             85
12354             58
12356             59
...              ...
18260            134
18263             61
18272            166
18283            756
18287             70

[1908 rows x 1 columns]

#### Selecciona pedidos de España superiores a 50 artículos

In [122]:
temp02 = orders.groupby(by = 'InvoiceNo')[['Quantity']].count()

temp02[temp02['Quantity'] > 50]

           Quantity
InvoiceNo
536401           64
536409           58
536412           81
536415           59
536464           85
...             ...
581414           71
581425           88
581433           72
581476           65
581538           74

[1653 rows x 1 columns]

#### Seleccionar todos los pedidos gratuitos

In [111]:
orders[orders['amount_spent'] == 0]

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
6914,9302,537197,22841,2010,12,7,14,round cake tin vintage green,1,2010-12-05 14:02:00,0.0,12647,Germany,0.0
22539,33576,539263,22580,2010,12,4,14,advent calendar gingham sack,4,2010-12-16 14:36:00,0.0,16560,United Kingdom,0.0
25379,40089,539722,22423,2010,12,2,13,regency cakestand 3 tier,10,2010-12-21 13:45:00,0.0,14911,EIRE,0.0
29080,47068,540372,22090,2011,1,4,16,paper bunting retrospot,24,2011-01-06 16:41:00,0.0,13081,United Kingdom,0.0
29082,47070,540372,22553,2011,1,4,16,plasters in tin skulls,24,2011-01-06 16:41:00,0.0,13081,United Kingdom,0.0
34494,56674,541109,22168,2011,1,4,15,organiser wood antique white,1,2011-01-13 15:10:00,0.0,15107,United Kingdom,0.0
53788,86789,543599,84535B,2011,2,4,13,fairy cakes notebook a6 size,16,2011-02-10 13:08:00,0.0,17560,United Kingdom,0.0
85671,130188,547417,22062,2011,3,3,10,ceramic bowl with love heart design,36,2011-03-23 10:25:00,0.0,13239,United Kingdom,0.0
92875,139453,548318,22055,2011,3,3,12,mini cake stand hanging strawbery,5,2011-03-30 12:45:00,0.0,13113,United Kingdom,0.0
97430,145208,548871,22162,2011,4,1,14,heart garland rustic padded,2,2011-04-04 14:42:00,0.0,14410,United Kingdom,0.0
107192,157042,550188,22636,2011,4,4,18,childs breakfast set circus parade,1,2011-04-14 18:57:00,0.0,12457,Switzerland,0.0
128641,187613,553000,47566,2011,5,4,15,party bunting,4,2011-05-12 15:21:00,0.0,17667,United Kingdom,0.0
137127,198383,554037,22619,2011,5,5,14,set of 6 soldier skittles,80,2011-05-20 14:13:00,0.0,12415,Australia,0.0
194648,279324,561284,22167,2011,7,2,12,oval wall mirror diamante,1,2011-07-26 12:24:00,0.0,16818,United Kingdom,0.0
197173,282912,561669,22960,2011,7,4,17,jam making set with jars,11,2011-07-28 17:09:00,0.0,12507,Spain,0.0
199711,285657,561916,M,2011,8,1,11,manual,1,2011-08-01 11:44:00,0.0,15581,United Kingdom,0.0
208950,298054,562973,23157,2011,8,4,11,set of 6 nativity magnets,240,2011-08-11 11:42:00,0.0,14911,EIRE,0.0
223931,314745,564651,23270,2011,8,5,14,set of 2 ceramic painted hearts,96,2011-08-26 14:19:00,0.0,14646,Netherlands,0.0
223932,314746,564651,23268,2011,8,5,14,set of 2 ceramic christmas reindeer,192,2011-08-26 14:19:00,0.0,14646,Netherlands,0.0
223933,314747,564651,22955,2011,8,5,14,36 foil star cake cases,144,2011-08-26 14:19:00,0.0,14646,Netherlands,0.0
223934,314748,564651,21786,2011,8,5,14,polkadot rain hat,144,2011-08-26 14:19:00,0.0,14646,Netherlands,0.0
256263,358655,568158,PADS,2011,9,7,12,pads to match all cushions,1,2011-09-25 12:22:00,0.0,16133,United Kingdom,0.0
259399,361825,568384,M,2011,9,2,9,manual,1,2011-09-27 09:46:00,0.0,12748,United Kingdom,0.0
273926,379913,569716,22778,2011,10,4,8,glass cloche small,2,2011-10-06 08:17:00,0.0,15804,United Kingdom,0.0
286507,395529,571035,M,2011,10,4,12,manual,1,2011-10-13 12:50:00,0.0,12446,RSA,0.0
307092,420404,572893,21208,2011,10,3,14,pastel colour honeycomb fan,5,2011-10-26 14:36:00,0.0,18059,United Kingdom,0.0
319882,436428,574138,23234,2011,11,4,11,biscuit tin vintage christmas,216,2011-11-03 11:26:00,0.0,12415,Australia,0.0
320049,436597,574175,22065,2011,11,4,11,christmas pudding trinket pot,12,2011-11-03 11:47:00,0.0,14110,United Kingdom,0.0
320407,436961,574252,M,2011,11,4,13,manual,1,2011-11-03 13:24:00,0.0,12437,France,0.0
322279,439361,574469,22385,2011,11,5,11,jumbo bag spaceboy design,12,2011-11-04 11:55:00,0.0,12431,Australia,0.0
328385,446125,574879,22625,2011,11,1,13,red kitchen scales,2,2011-11-07 13:22:00,0.0,13014,United Kingdom,0.0
329006,446793,574920,22899,2011,11,1,16,children's apron dolly girl,1,2011-11-07 16:34:00,0.0,13985,United Kingdom,0.0
329007,446794,574920,23480,2011,11,1,16,mini lights woodland mushrooms,1,2011-11-07 16:34:00,0.0,13985,United Kingdom,0.0
334242,454463,575579,22437,2011,11,4,11,set of 9 black skull balloons,20,2011-11-10 11:49:00,0.0,13081,United Kingdom,0.0
334243,454464,575579,22089,2011,11,4,11,paper bunting vintage paisley,24,2011-11-10 11:49:00,0.0,13081,United Kingdom,0.0
352746,479079,577129,22464,2011,11,4,19,hanging metal heart lantern,4,2011-11-17 19:52:00,0.0,15602,United Kingdom,0.0
353097,479546,577168,M,2011,11,5,10,manual,1,2011-11-18 10:42:00,0.0,12603,Germany,0.0
354170,480649,577314,23407,2011,11,5,13,set of 2 trays home sweet home,2,2011-11-18 13:23:00,0.0,12444,Norway,0.0
358629,485985,577696,M,2011,11,1,11,manual,1,2011-11-21 11:57:00,0.0,16406,United Kingdom,0.0
370473,502122,578841,84826,2011,11,5,15,asstd design 3d paper stickers,12540,2011-11-25 15:57:00,0.0,13256,United Kingdom,0.0

#### Seleccionar todos los pedidos que sean 'lunch bag
#### Pista: Utilice las funciones de cadena

In [ ]:
# orders[orders['Description'] == '\lunch']

<>:1: SyntaxWarning: invalid escape sequence '\l'
<>:1: SyntaxWarning: invalid escape sequence '\l'
C:\Users\david\AppData\Local\Temp\ipykernel_13412\1242983974.py:1: SyntaxWarning: invalid escape sequence '\l'
  orders[orders['Description'] == '\lunch']

Empty DataFrame
Columns: [Unnamed: 0, InvoiceNo, StockCode, year, month, day, hour, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country, amount_spent]
Index: []

#### Seleccione todos los pedidos realizados en 2011 y que sean «lunch bag».

In [52]:
# your answer here

#### Muestra la distribución de frecuencias del importe gastado en España.

In [53]:
# your answer here

#### Seleccione todos los pedidos realizados en el mes de agosto

In [128]:
orders[orders['month'] == 8]

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
199475,285421,561904,22075,2011,8,1,8,6 ribbons elegant christmas,96,2011-08-01 08:30:00,1.45,17941,United Kingdom,139.20
199476,285422,561904,85049E,2011,8,1,8,scandinavian reds ribbons,156,2011-08-01 08:30:00,1.06,17941,United Kingdom,165.36
199477,285423,561905,21385,2011,8,1,9,ivory hanging decoration heart,24,2011-08-01 09:31:00,0.85,14947,United Kingdom,20.40
199478,285424,561905,84970L,2011,8,1,9,single heart zinc t-light holder,12,2011-08-01 09:31:00,0.95,14947,United Kingdom,11.40
199479,285425,561905,84970S,2011,8,1,9,hanging heart zinc t-light holder,12,2011-08-01 09:31:00,0.85,14947,United Kingdom,10.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226483,320688,565067,22644,2011,8,3,17,ceramic cherry cake money bank,2,2011-08-31 17:16:00,1.45,15856,United Kingdom,2.90
226484,320689,565067,22645,2011,8,3,17,ceramic heart fairy cake money bank,2,2011-08-31 17:16:00,1.45,15856,United Kingdom,2.90
226485,320690,565067,22637,2011,8,3,17,piggy bank retrospot,2,2011-08-31 17:16:00,2.55,15856,United Kingdom,5.10
226486,320691,565067,22646,2011,8,3,17,ceramic strawberry cake money bank,2,2011-08-31 17:16:00,1.45,15856,United Kingdom,2.90
226487,320692,565067,22741,2011,8,3,17,funky diva pen,48,2011-08-31 17:16:00,0.85,15856,United Kingdom,40.80

#### Seleccione cuántos pedidos se realizan por países en el mes de agosto
##### Pista: Utilice value_counts()

In [133]:
orders[orders['month'] == 8].groupby(by = ['Country']).value_counts()

Country      Unnamed: 0  InvoiceNo  StockCode  year  month  day  hour  Description                          Quantity  InvoiceDate          UnitPrice  CustomerID  amount_spent
Australia    299898      563179     23268      2011  8      5    14    set of 2 ceramic christmas reindeer  12        2011-08-12 14:19:00  1.45       12431       17.40           1
             299899      563179     23344      2011  8      5    14    jumbo bag 50's christmas             10        2011-08-12 14:19:00  2.08       12431       20.80           1
             299900      563179     21164      2011  8      5    14    home sweet home metal sign           6         2011-08-12 14:19:00  2.95       12431       17.70           1
             299901      563179     21731      2011  8      5    14    red toadstool led night light        288       2011-08-12 14:19:00  1.45       12431       417.60          1
             299902      563179     23158      2011  8      5    14    set of 5 lucky cat magnets           12        2011-08-12 14:19:00  2.08       12431       24.96           1
                                                                                                                                                                                 ..
Unspecified  308810      564051     23007      2011  8      1    13     spaceboy baby gift set              1         2011-08-22 13:32:00  16.95      14265       16.95           1
             308811      564051     21833      2011  8      1    13    camouflage led torch                 12        2011-08-22 13:32:00  1.69       14265       20.28           1
             308812      564051     23081      2011  8      1    13    green metal box army supplies        2         2011-08-22 13:32:00  8.25       14265       16.50           1
             308813      564051     23046      2011  8      1    13    paper lantern 9 point deluxe star    2         2011-08-22 13:32:00  6.65       14265       13.30           1
             308814      564051     23045      2011  8      1    13    paper lantern 5 point star moon      4         2011-08-22 13:32:00  4.15       14265       16.60           1
Name: count, Length: 27013, dtype: int64

#### ¿Cuál es el gasto medio por país?

In [56]:
# your answer here

#### ¿Cuál es el artículo más caro?

In [57]:
# your answer here

#### ¿Cuál fue la cantidad media gastada al año?

In [58]:
# your answer here